[tool.pyright]
exclude = [
  'omnigibson/data',
  'omnigibson/docs',
  'omnigibson/docker'
]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
extend-exclude = ["omnigibson/utils/pynvml_utils.py", "omnigibson/data"]

# Same as Black.
line-length = 120
indent-width = 4

# Assume Python 3.10
target-version = "py310"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F"]
ignore = [
    "E731",  # lambda expressions assigned to variables. this keeps some files short.
    "E722",  # bare except. We don't want to dig deep to find what exception is being raised.
    "E741",  # ambiguous variable name for the character 'l', but we use it a lot for length.
]

[tool.ruff.format]
# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
docstring-code-format = true
