defaults:
  - _self_  # all below configs will override this conf.yaml
  - robot: r1pro
  - task: behavior
  - policy: ???

env_wrapper: 
  _target_: omnigibson.learning.wrappers.RGBLowResWrapper
policy_name: ???  # filled by policy
headless: true  # whether to run in headless mode (no GUI)
eval_on_train_instances: false  # whether to eval on training instances
eval_instance_ids: null  # specific list of instance ids to eval on, if null test on all instances
write_video: true # whether we record videos during rollout
partial_scene_load: false  # whether to only load task-relevant rooms for a specific task
max_steps: null  # max steps per rollout episode, setting to null will use the default value (2 x average human demo completion steps)
log_path: ???
